---
title: "05_blh-try-leaflet"
author: "Brooke Hawkins"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(sf)
library(leaflet)
```

## Load data

```{r}
# load grid
grid_5km <- read_sf(here('GIS_layers', 'fivekm_grid_polys_shore_lamb.shp'))

# load some crab data
vms_crab_data <- read_rds(here('Confidential', 'data', 'archive_processed', 'interim', 'vms_interpolated_w_grd_5km.rds'))

# this is not following the proper workflow, see notebook 03 for that, this is just quick and dirty getting one month of data to vis
vms_crab_vis_data <- vms_crab_data %>%
  mutate(year = year(date), month = month(date)) %>% # add year and month columns
  filter(year == 2018 & month == 11) %>% # filter for one year
  group_by(year, month, GRID5KM_ID) %>% # group by year, month, cell
  summarise(n_pings = n(), .groups = "drop") %>% # count pings
  filter(n_pings >= 3) # confidentiality
```

At this point, `grid_5km` is a simple features object with multipolygon geometry. `vms_crab_vis_data` is a tibble (ungrouped). They can be joined together using GRID5KM_ID.

```{r}
# join data
joined_df <- vms_crab_vis_data %>% 
  left_join(grid_5km, by = 'GRID5KM_ID') %>% 
  st_as_sf() %>%
  st_transform(crs = 4326)
```

`joined_data` is a simple features object with multipolygon geometry, transformed from the custom coordinate system to lat/long for leaflet.

## Try Leaflet

Helpful resources:

* https://rstudio.github.io/leaflet/articles/choropleths.html
* https://rstudio.github.io/leaflet/articles/colors.html
* https://rstudio.github.io/leaflet/articles/legends.html

```{r}
# create a color palette
pal <- colorNumeric(
  palette = "Blues",
  domain = joined_df$n_pings)

# add labels
labels <- sprintf(
  "<strong>Cell %g</strong><br/>%g pings",
  joined_df$GRID5KM_ID, joined_df$n_pings
) %>% lapply(htmltools::HTML)

# create a generic map
leaflet(joined_df) %>%
  addPolygons(fillColor = ~pal(n_pings),
              stroke = FALSE,
              fillOpacity = 1,
              label = labels) %>%
  addLegend("bottomright",
            pal = pal, 
            values = ~n_pings,
            title = "Number of Pings",
            opacity = 1) %>%
  addTiles()
```
